# Generated by Django 5.1.3 on 2024-12-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
